# Stage 1: Build
FROM node:20-alpine AS builder
# Tambahkan tool build untuk Sass/Sharp
RUN apk add --no-cache libc6-compat python3 make g++
WORKDIR /app
RUN npm i -g pnpm

# Alokasikan RAM lebih besar untuk Node saat build
ENV NODE_OPTIONS="--max-old-space-size=2048"

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY . .
RUN pnpm run build

# Stage 2: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copy aset publik
COPY --from=builder /app/public ./public

# Copy hasil standalone
COPY --from=builder /app/.next/standalone ./

# Copy folder static ke dalam struktur yang benar agar CSS muncul
RUN mkdir -p .next
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]