services:
  portfolio:
    image: ghcr.io/mfaris2002/my_porto1:latest # Sesuaikan username/repo
    container_name: my-portfolio
    ports:
      - "3000:3000"
    restart: always
    # Kita tidak pakai 'build:' lagi di sini supaya VPS tidak kerja berat
