# Stage 1: Build
FROM node:20-alpine AS builder
RUN apk add --no-cache libc6-compat
WORKDIR /app
RUN npm i -g pnpm

# Salin package.json dan coba salin lockfile jika ada
COPY package.json ./
COPY pnpm-lock.yaml* ./ 

# Hapus flag --frozen-lockfile agar tidak error jika lockfile tidak ada
RUN pnpm install

COPY . .
RUN pnpm run build

# Stage 2: Runner
FROM node:20-alpine AS runner
WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
CMD ["node", "server.js"]