name: Build and Deploy Portfolio

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  # Kita tulis manual saja dengan huruf kecil agar aman dan pasti berhasil
  IMAGE_NAME: mfaris2002/my-porto1 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          # Di sini kita panggil IMAGE_NAME yang sudah huruf kecil
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /var/www/my_porto1
            git pull origin main
            # Pastikan docker-compose menggunakan nama image yang huruf kecil juga
            docker compose pull
            docker compose up -d
            docker image prune -f